# PlatformIO Project Configuration Override
# ------------------------------------------------------------------------------
# This file enables the Auto Save Usermod
# ------------------------------------------------------------------------------

[platformio]
default_envs = esp32s3mini_4MB_psram

# Configure ESP32-S3 Mini with Auto Save Usermod
[env:esp32s3mini_4MB_psram]
custom_usermods = usermod_v2_auto_save    ; Include auto save usermod in build
build_flags = ${esp32s3.build_flags}
  -D AUTOSAVE_AFTER_SEC=2                 ; Save after 2 seconds of inactivity
  -D AUTOSAVE_PRESET_NUM=200              ; Save to preset 200
  -D USERMOD_AUTO_SAVE_ON_BOOT=true       ; Load autosaved preset on boot
